font_family      family="CaskaydiaCove Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

shell /bin/zsh

close_on_child_death yes
clipboard_control write-clipboard write-primary read-clipboard read-primary
confirm_os_window_close 0

# vim
map ctrl+v nth_window 0

# shell
map ctrl+space nth_window 2

include Catppuccin-Mocha.conf
