# https://wiki.hypr.land/Configuring

#monitor=,preferred,auto,1

$terminal = kitty
$menu = walker
$browser = google-chrome-stable --disable-gpu-compositing

source = services.conf

xwayland {
    # fixes blurry text on xwayland apps e.g. discord
    force_zero_scaling = true
}

source = style.conf
source = input.conf
source = keybinds.conf
