# https://wiki.hypr.land/Configuring

monitor=,preferred,auto-left,auto

$terminal = kitty
$menu = walker
$browser = google-chrome-stable

exec-once = elephant &
exec-once = $menu --gapplication-service &
exec-once = waybar &

ecosystem {
  enforce_permissions = 1
}

source = style.conf
source = input.conf
source = keybinds.conf
