# https://wiki.hypr.land/Configuring

monitor=,preferred,auto-left,auto

$terminal = kitty
$menu = walker
$browser = google-chrome-stable

exec-once = hyprpaper
exec-once = ~/.config/hypr/wallpaper.zsh
exec-once = 1password --silent
exec-once = elephant
exec-once = $menu --gapplication-service
exec-once = waybar

ecosystem {
  enforce_permissions = 1
}

xwayland {
    # fixes blurry text on xwayland apps e.g. discord
    force_zero_scaling = true
}

source = style.conf
source = input.conf
source = keybinds.conf
