# auth
exec-once = systemctl --user start hyprpolkitagent

# desktop
exec-once = hyprpaper
exec-once = hypridle

# start 1pass daemon
exec-once = 1password --silent

# picker daemons
exec-once = elephant
exec-once = $menu --gapplication-service

# status bar
exec-once = waybar
